import math
from typing import Dict, List, Set, Any

def optimize_token_budget(
    files_metadata: Dict[str, Dict[str, Any]],
    dependency_graph: Dict[str, List[str]],
    budget: int,
    dep_weight: float = 0.5,
    git_weight: float = 0.5,
    pinned_files: List[str] = None,
    excluded_files: List[str] = None
) -> List[str]:
    """
    Selects files that maximize total score within the token budget.
    
    Parameters:
    - files_metadata: metadata dict generated by scanner
    - dependency_graph: adjacency list of imports (A imports B)
    - budget: token limit slider value
    - dep_weight: importance slider for dependencies
    - git_weight: importance slider for git recency/activity
    - pinned_files: list of files that must be included first
    - excluded_files: list of files that must be omitted
    """
    if pinned_files is None:
        pinned_files = []
    if excluded_files is None:
        excluded_files = []

    excluded_set = set(excluded_files)
    selected_files: Set[str] = set()
    current_tokens = 0

    # 1. Force add pinned files that are not excluded and fit within budget
    # Sort pinned files by token size so we fit smaller ones first, or respect order
    for path in pinned_files:
        if path in excluded_set or path not in files_metadata:
            continue
        tokens = files_metadata[path].get("tokens", 0)
        if current_tokens + tokens <= budget:
            selected_files.add(path)
            current_tokens += tokens

    # 2. Compute combined scores for remaining files
    remaining_files = [
        path for path in files_metadata
        if path not in selected_files and path not in excluded_set
    ]

    if not remaining_files:
        return list(selected_files)

    # Calculate raw scores
    raw_scores: Dict[str, float] = {}
    for path in remaining_files:
        meta = files_metadata[path]
        dep_score = meta.get("dependency_score", 0.0)
        
        # Git score combines recency and activity (frequency)
        git_recency = meta.get("recency_score", 0.0)
        git_activity = meta.get("activity_score", 0.0)
        # Weight recency slightly higher than absolute commit count frequency
        git_score = 0.6 * git_recency + 0.4 * git_activity
        
        # Combined score (weighted average)
        total_weight = dep_weight + git_weight
        if total_weight > 0:
            combined = (dep_weight * dep_score + git_weight * git_score) / total_weight
        else:
            combined = 0.1 # default low baseline
            
        # Give a small base score to avoid 0 scores for files with no git history/imports
        raw_scores[path] = max(0.01, combined)

    # 3. Propagate score boost based on imports of pinned/already selected files
    # If a selected file A imports B, B gets a boost because it's required context
    boosted_scores = raw_scores.copy()
    for path in list(selected_files):
        # Find imports of this file
        imports = dependency_graph.get(path, [])
        for imp in imports:
            if imp in boosted_scores:
                # Add 30% of average score as a dependency propagation boost
                boosted_scores[imp] += 0.3

    # 4. Greedy Selection: Sort by value density (Score / Tokens^alpha)
    # We use alpha = 0.4 to penalize large files while not selecting *only* tiny files.
    alpha = 0.4
    density_list = []
    for path in remaining_files:
        tokens = max(1, files_metadata[path].get("tokens", 0))
        score = boosted_scores.get(path, 0.01)
        # Value density metric
        density = score / (tokens ** alpha)
        density_list.append((path, density, tokens))

    # Sort descending by density
    density_list.sort(key=lambda x: x[1], reverse=True)

    # 5. Greedy fill
    for path, density, tokens in density_list:
        if current_tokens + tokens <= budget:
            selected_files.add(path)
            current_tokens += tokens
            
            # Dynamically boost imports of newly selected files
            imports = dependency_graph.get(path, [])
            # Re-evaluating remaining might be too complex, but we can do a simple one-step propagation:
            # We already did it for pinned files, and this greedy pass runs in sorted order.

    # Re-order files so pinned ones are at the top, followed by selected ones,
    # maintaining their original layout or relative paths for clean output.
    # Let's return them in alphabetical/path order for consistent viewing,
    # but separate the list into a structured output.
    return sorted(list(selected_files))
